# Default values for the API Gateway Helm chart

replicaCount: 1

image:
  repository: ghcr.io/nooshet-backend/api-gateway
  tag: latest
  pullPolicy: IfNotPresent
  imagePullSecrets: []

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

hpa:
  enabled: false
  minReplicas: "1"
  maxReplicas: "3"
  cpuUtilization: "90"
  memoryUtilization: "450Mi"

resources:
  limits:
    memory: 512Mi
    cpu: 500m
  requests:
    cpu: 250m
    memory: 256Mi

env:
  JWT_SECRET: "change-me-in-prod"
  JWT_ISSUER: "nooshet"
  SPRING_PROFILES_ACTIVE: "dev"
  SPRING_REDIS_HOST: "redis"
  SPRING_REDIS_PORT: "6379"
  SPRING_REDIS_TIMEOUT: "2000ms"
  IDENTITY_SERVICE_URL: "http://identity-service:8080"
  USER_SERVICE_URL: "http://user-service:8080"
  JAVA_OPTS: "-XX:TieredStopAtLevel=1 -Xss256k -Xmx448m"

istio:
  enabled: true
  pathPrefix: ""
  gateway:
    create: true
    name: public-gateway
    host: "*"
    port: 80
    selector:
      istio: ingressgateway
  virtualService:
    create: true
    hosts:
      - "*"
    corsPolicy:
      allowOrigins:
        - exact: "*"
      allowMethods:
        - POST
        - GET
        - OPTIONS
        - PUT
        - DELETE
      allowHeaders:
        - authorization
        - content-type
        - keep-alive
        - user-agent
        - cache-control
        - content-transfer-encoding
        - x-accept-content-transfer-encoding
        - x-accept-response-streaming
        - x-user-agent
        - x-grpc-web
        - x-internal-token
        - x-user-id
        - x-user-email
        - x-user-roles
        - x-request-id
      maxAge: 100s
    http:
      # Service API Docs Routes
      - match:
          - uri:
              prefix: /v3/api-docs/identity-service
        rewrite:
          uri: /v3/api-docs
        route:
          - destination:
              host: identity-service
              port:
                number: 8080
      - match:
          - uri:
              prefix: /v3/api-docs/user-service
        rewrite:
          uri: /v3/api-docs
        route:
          - destination:
              host: user-service
              port:
                number: 8080
      # General Gateway Routes
      - match:
          - uri:
              prefix: /api/v1/
          - uri:
              prefix: /swagger-ui
          - uri:
              prefix: /v3/api-docs
          - uri:
              prefix: /webjars
          - uri:
              exact: /swagger-ui.html
        route:
          - destination:
              host: api-gateway
              port:
                number: 80

destinationRule:
  connectionPool:
    http:
      http1MaxPendingRequests: 100
      http2MaxRequests: 1000
    tcp:
      maxConnections: 100
  loadBalancer:
    simple: ROUND_ROBIN
  outlierDetection:
    consecutive5xxErrors: 5
    interval: 30s
    baseEjectionTime: 30s
    maxEjectionPercent: 50
