apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "api-gateway.fullname" . }}-virtual
spec:
  gateways:
    - {{ include "api-gateway.fullname" . }}-gateway
  hosts:
    {{- range .Values.istio.virtualService.hosts }}
    - {{ . | quote }}
    {{- end }}
  http:
    {{- range .Values.istio.virtualService.http }}
    - match:
        {{- range .match }}
        - uri:
            {{- if .uri.prefix }}
            prefix: {{ .uri.prefix }}
            {{- else if .uri.exact }}
            exact: {{ .uri.exact }}
            {{- else if .uri.regex }}
            regex: {{ .uri.regex }}
            {{- end }}
        {{- end }}
      {{- if .rewrite }}
      rewrite:
        uri: {{ .rewrite.uri }}
      {{- end }}
      route:
        {{- range .route }}
        - destination:
            host: {{ .destination.host }}
            port:
              number: {{ .destination.port.number }}
        {{- end }}
    {{- end }}
